version: '2.0'
services:

  postgres:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: jsmartbot
      POSTGRES_PASSWORD: jsmartbot
      PGDATA: /data/postgres
    volumes:
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8002:80
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: orsevic@gmail.com
      PGADMIN_DEFAULT_PASSWORD: jsmartbot
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
