server.port: 8081
spring.application.name: bot

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    change-log: classpath:liquibase/migration.yml
    contexts: common

jsmartbot.environment.ip: 192.168.99.100

spring.datasource:
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://${jsmartbot.environment.ip}:5434/jsmartbot?connectTimeout=120&currentSchema=bot,public"
  username: "jsmartbot"
  password: "jsmartbot"
  min-idle: 4
  max-idle: 8
  max-active: 8
  max-wait: 60000
  test-on-borrow: true
  validation-interval: 5000
  validation-query: "SELECT 1;"

---
spring:
  profiles: local
jsmartbot.environment.ip: 127.0.0.1
